apiVersion: v1
kind: Secret
metadata:
  name: credentials-micro
  namespace: default
type: Opaque # Tipo por defecto, se puede omitir
stringData: # Para datos en texto plano (se codifican en base64 autom√°ticamente)
  username: ""
  password: ""
